// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { ListApiKeysData, ListApiKeysResponse, ListApiKeysError, CreateApiKeyData, CreateApiKeyResponse, CreateApiKeyError, RevokeApiKeyData, RevokeApiKeyResponse, RevokeApiKeyError, LoginRequestData, LoginRequestResponse, LoginRequestError, LoginVerifyData, LoginVerifyResponse, LoginVerifyError, LogoutData, LogoutResponse, LogoutError, GetMeData, GetMeResponse, GetMeError, ListCompaniesData, ListCompaniesResponse, ListCompaniesError, CreateCompanyData, CreateCompanyResponse, CreateCompanyError, InviteCompanyMemberData, InviteCompanyMemberResponse, InviteCompanyMemberError, ListCompanyMembersData, ListCompanyMembersResponse, ListCompanyMembersError, RemoveCompanyMemberData, RemoveCompanyMemberResponse, RemoveCompanyMemberError, UpdateCompanyMemberRoleData, UpdateCompanyMemberRoleResponse, UpdateCompanyMemberRoleError, ListCompanyRolesData, ListCompanyRolesResponse, ListCompanyRolesError, SelectCompanyData, SelectCompanyResponse, SelectCompanyError, ListFeatureFlagsData, ListFeatureFlagsResponse, ListFeatureFlagsError, AdminListFeatureFlagsData, AdminListFeatureFlagsResponse, AdminListFeatureFlagsError, AdminUpsertFeatureFlagsData, AdminUpsertFeatureFlagsResponse, AdminUpsertFeatureFlagsError, GetUserMeData, GetUserMeResponse, GetUserMeError, UpdateUserMeData, UpdateUserMeResponse, UpdateUserMeError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List API keys for selected company
 */
export const listApiKeys = <ThrowOnError extends boolean = false>(options?: Options<ListApiKeysData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListApiKeysResponse, ListApiKeysError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/apikeys',
        ...options
    });
};

/**
 * Create a new API key
 */
export const createApiKey = <ThrowOnError extends boolean = false>(options: Options<CreateApiKeyData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateApiKeyResponse, CreateApiKeyError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/apikeys',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Revoke an API key
 */
export const revokeApiKey = <ThrowOnError extends boolean = false>(options: Options<RevokeApiKeyData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<RevokeApiKeyResponse, RevokeApiKeyError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/apikeys/{id}/revoke',
        ...options
    });
};

/**
 * Request OTP login
 */
export const loginRequest = <ThrowOnError extends boolean = false>(options: Options<LoginRequestData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<LoginRequestResponse, LoginRequestError, ThrowOnError>({
        url: '/api/auth/login-request',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Verify OTP and issue session token
 */
export const loginVerify = <ThrowOnError extends boolean = false>(options: Options<LoginVerifyData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<LoginVerifyResponse, LoginVerifyError, ThrowOnError>({
        url: '/api/auth/login-verify',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Logout
 */
export const logout = <ThrowOnError extends boolean = false>(options?: Options<LogoutData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<LogoutResponse, LogoutError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/auth/logout',
        ...options
    });
};

/**
 * Get current user profile
 */
export const getMe = <ThrowOnError extends boolean = false>(options?: Options<GetMeData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetMeResponse, GetMeError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/auth/me',
        ...options
    });
};

/**
 * List companies for the current user
 */
export const listCompanies = <ThrowOnError extends boolean = false>(options?: Options<ListCompaniesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListCompaniesResponse, ListCompaniesError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/companies',
        ...options
    });
};

/**
 * Create a new company
 */
export const createCompany = <ThrowOnError extends boolean = false>(options: Options<CreateCompanyData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateCompanyResponse, CreateCompanyError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/companies',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Invite a user to the selected company
 */
export const inviteCompanyMember = <ThrowOnError extends boolean = false>(options: Options<InviteCompanyMemberData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<InviteCompanyMemberResponse, InviteCompanyMemberError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/companies/invite',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * List members of the selected company (admin only)
 */
export const listCompanyMembers = <ThrowOnError extends boolean = false>(options?: Options<ListCompanyMembersData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListCompanyMembersResponse, ListCompanyMembersError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/companies/members',
        ...options
    });
};

/**
 * Remove a member from the selected company
 */
export const removeCompanyMember = <ThrowOnError extends boolean = false>(options: Options<RemoveCompanyMemberData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<RemoveCompanyMemberResponse, RemoveCompanyMemberError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/companies/members/{userId}',
        ...options
    });
};

/**
 * Update a member's role in the selected company
 */
export const updateCompanyMemberRole = <ThrowOnError extends boolean = false>(options: Options<UpdateCompanyMemberRoleData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<UpdateCompanyMemberRoleResponse, UpdateCompanyMemberRoleError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/companies/members/{userId}/role',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * List available company roles
 */
export const listCompanyRoles = <ThrowOnError extends boolean = false>(options?: Options<ListCompanyRolesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListCompanyRolesResponse, ListCompanyRolesError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/companies/roles',
        ...options
    });
};

/**
 * Select active company
 */
export const selectCompany = <ThrowOnError extends boolean = false>(options: Options<SelectCompanyData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<SelectCompanyResponse, SelectCompanyError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/companies/{id}/select',
        ...options
    });
};

/**
 * List feature flags for the current user's selected company
 */
export const listFeatureFlags = <ThrowOnError extends boolean = false>(options?: Options<ListFeatureFlagsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListFeatureFlagsResponse, ListFeatureFlagsError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/feature-flags',
        ...options
    });
};

/**
 * Admin: get full context (flags, companies, keys)
 */
export const adminListFeatureFlags = <ThrowOnError extends boolean = false>(options?: Options<AdminListFeatureFlagsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<AdminListFeatureFlagsResponse, AdminListFeatureFlagsError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/feature-flags/admin',
        ...options
    });
};

/**
 * Admin: upsert a flag across one or more companies
 */
export const adminUpsertFeatureFlags = <ThrowOnError extends boolean = false>(options: Options<AdminUpsertFeatureFlagsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AdminUpsertFeatureFlagsResponse, AdminUpsertFeatureFlagsError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/feature-flags/admin',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get current user profile
 */
export const getUserMe = <ThrowOnError extends boolean = false>(options?: Options<GetUserMeData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetUserMeResponse, GetUserMeError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/users/me',
        ...options
    });
};

/**
 * Update current user profile
 */
export const updateUserMe = <ThrowOnError extends boolean = false>(options: Options<UpdateUserMeData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<UpdateUserMeResponse, UpdateUserMeError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/users/me',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};