// This file is auto-generated by @hey-api/openapi-ts

export type ApiKeyCreateRequestReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    name: string;
};

export type ApiKeyCreateRequestWritable = {
    name: string;
};

export type ApiKeyCreateResponseReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    apiKey: ApiKeyInfo;
};

export type ApiKeyCreateResponseWritable = {
    apiKey: ApiKeyInfo;
};

export type ApiKeyInfo = {
    createdAt: string;
    id: number;
    lastUsedAt?: string;
    name: string;
    prefix: string;
    revokedAt?: string;
    token?: string;
};

export type ApiKeyListResponseReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    apiKeys: Array<ApiKeyInfo> | null;
};

export type ApiKeyListResponseWritable = {
    apiKeys: Array<ApiKeyInfo> | null;
};

export type AdminContextResponseReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    companies: Array<CompanyOption> | null;
    flags: Array<AdminFlag> | null;
    suggestedKeys: Array<string> | null;
};

export type AdminContextResponseWritable = {
    companies: Array<CompanyOption> | null;
    flags: Array<AdminFlag> | null;
    suggestedKeys: Array<string> | null;
};

export type AdminFlag = {
    companyId: number;
    companyName: string;
    enabled: boolean;
    flagKey: string;
    id: number;
    updatedAt: string;
};

export type AuthProfileReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    email: string;
    id: number;
    name: string;
    selectedCompanyId: number;
};

export type AuthProfileWritable = {
    email: string;
    id: number;
    name: string;
    selectedCompanyId: number;
};

export type CompanyCreateRequestReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    name: string;
};

export type CompanyCreateRequestWritable = {
    name: string;
};

export type CompanyCreateResponseReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    company: CompanyInfo;
};

export type CompanyCreateResponseWritable = {
    company: CompanyInfo;
};

export type CompanyInfo = {
    createdAt: string;
    id: number;
    isOwner: boolean;
    name: string;
    role: string;
};

export type CompanyListResponseReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    companies: Array<CompanyInfo> | null;
};

export type CompanyListResponseWritable = {
    companies: Array<CompanyInfo> | null;
};

export type CompanyOption = {
    id: number;
    name: string;
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModelReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type ErrorModelWritable = {
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type FlagListResponseReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    flags: {
        [key: string]: boolean;
    };
};

export type FlagListResponseWritable = {
    flags: {
        [key: string]: boolean;
    };
};

export type InviteRequestReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    email: string;
    name: string;
    role: string;
};

export type InviteRequestWritable = {
    email: string;
    name: string;
    role: string;
};

export type InviteResponseReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    member: Member;
};

export type InviteResponseWritable = {
    member: Member;
};

export type LoginRequestReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    email: string;
};

export type LoginRequestWritable = {
    email: string;
};

export type Member = {
    email: string;
    joinedAt: string;
    name: string;
    role: string;
    userId: number;
};

export type MemberListResponseReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    members: Array<Member> | null;
};

export type MemberListResponseWritable = {
    members: Array<Member> | null;
};

export type ProfileReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    createdAt: string;
    email: string;
    id: number;
    name: string;
    selectedCompanyId: number;
};

export type ProfileWritable = {
    createdAt: string;
    email: string;
    id: number;
    name: string;
    selectedCompanyId: number;
};

export type Role = {
    label: string;
    value: string;
};

export type RolesResponseReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    roles: Array<Role> | null;
};

export type RolesResponseWritable = {
    roles: Array<Role> | null;
};

export type UpdateProfileRequestReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    name: string;
};

export type UpdateProfileRequestWritable = {
    name: string;
};

export type UpdateRoleBodyReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    role: string;
};

export type UpdateRoleBodyWritable = {
    role: string;
};

export type UpsertRequestReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    allCompanies: boolean;
    companyIds: Array<number> | null;
    enabled: boolean;
    flagKey: string;
};

export type UpsertRequestWritable = {
    allCompanies: boolean;
    companyIds: Array<number> | null;
    enabled: boolean;
    flagKey: string;
};

export type UpsertResponseReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    flags: Array<AdminFlag> | null;
};

export type UpsertResponseWritable = {
    flags: Array<AdminFlag> | null;
};

export type VerifyRequestReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    email: string;
    otp: string;
};

export type VerifyRequestWritable = {
    email: string;
    otp: string;
};

export type VerifyResponseReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    profile: AuthProfileReadable;
    token: string;
};

export type VerifyResponseWritable = {
    profile: AuthProfileWritable;
    token: string;
};

export type ListApiKeysData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/apikeys';
};

export type ListApiKeysErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type ListApiKeysError = ListApiKeysErrors[keyof ListApiKeysErrors];

export type ListApiKeysResponses = {
    /**
     * OK
     */
    200: ApiKeyListResponseReadable;
};

export type ListApiKeysResponse = ListApiKeysResponses[keyof ListApiKeysResponses];

export type CreateApiKeyData = {
    body: ApiKeyCreateRequestWritable;
    path?: never;
    query?: never;
    url: '/api/apikeys';
};

export type CreateApiKeyErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type CreateApiKeyError = CreateApiKeyErrors[keyof CreateApiKeyErrors];

export type CreateApiKeyResponses = {
    /**
     * Created
     */
    201: ApiKeyCreateResponseReadable;
};

export type CreateApiKeyResponse = CreateApiKeyResponses[keyof CreateApiKeyResponses];

export type RevokeApiKeyData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/apikeys/{id}/revoke';
};

export type RevokeApiKeyErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type RevokeApiKeyError = RevokeApiKeyErrors[keyof RevokeApiKeyErrors];

export type RevokeApiKeyResponses = {
    /**
     * No Content
     */
    204: void;
};

export type RevokeApiKeyResponse = RevokeApiKeyResponses[keyof RevokeApiKeyResponses];

export type LoginRequestData = {
    body: LoginRequestWritable;
    path?: never;
    query?: never;
    url: '/api/auth/login-request';
};

export type LoginRequestErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type LoginRequestError = LoginRequestErrors[keyof LoginRequestErrors];

export type LoginRequestResponses = {
    /**
     * No Content
     */
    204: void;
};

export type LoginRequestResponse = LoginRequestResponses[keyof LoginRequestResponses];

export type LoginVerifyData = {
    body: VerifyRequestWritable;
    path?: never;
    query?: never;
    url: '/api/auth/login-verify';
};

export type LoginVerifyErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type LoginVerifyError = LoginVerifyErrors[keyof LoginVerifyErrors];

export type LoginVerifyResponses = {
    /**
     * OK
     */
    200: VerifyResponseReadable;
};

export type LoginVerifyResponse = LoginVerifyResponses[keyof LoginVerifyResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * No Content
     */
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type GetMeErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
    /**
     * OK
     */
    200: AuthProfileReadable;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type ListCompaniesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/companies';
};

export type ListCompaniesErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type ListCompaniesError = ListCompaniesErrors[keyof ListCompaniesErrors];

export type ListCompaniesResponses = {
    /**
     * OK
     */
    200: CompanyListResponseReadable;
};

export type ListCompaniesResponse = ListCompaniesResponses[keyof ListCompaniesResponses];

export type CreateCompanyData = {
    body: CompanyCreateRequestWritable;
    path?: never;
    query?: never;
    url: '/api/companies';
};

export type CreateCompanyErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type CreateCompanyError = CreateCompanyErrors[keyof CreateCompanyErrors];

export type CreateCompanyResponses = {
    /**
     * Created
     */
    201: CompanyCreateResponseReadable;
};

export type CreateCompanyResponse = CreateCompanyResponses[keyof CreateCompanyResponses];

export type InviteCompanyMemberData = {
    body: InviteRequestWritable;
    path?: never;
    query?: never;
    url: '/api/companies/invite';
};

export type InviteCompanyMemberErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type InviteCompanyMemberError = InviteCompanyMemberErrors[keyof InviteCompanyMemberErrors];

export type InviteCompanyMemberResponses = {
    /**
     * Created
     */
    201: InviteResponseReadable;
};

export type InviteCompanyMemberResponse = InviteCompanyMemberResponses[keyof InviteCompanyMemberResponses];

export type ListCompanyMembersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/companies/members';
};

export type ListCompanyMembersErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type ListCompanyMembersError = ListCompanyMembersErrors[keyof ListCompanyMembersErrors];

export type ListCompanyMembersResponses = {
    /**
     * OK
     */
    200: MemberListResponseReadable;
};

export type ListCompanyMembersResponse = ListCompanyMembersResponses[keyof ListCompanyMembersResponses];

export type RemoveCompanyMemberData = {
    body?: never;
    path: {
        userId: number;
    };
    query?: never;
    url: '/api/companies/members/{userId}';
};

export type RemoveCompanyMemberErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type RemoveCompanyMemberError = RemoveCompanyMemberErrors[keyof RemoveCompanyMemberErrors];

export type RemoveCompanyMemberResponses = {
    /**
     * No Content
     */
    204: void;
};

export type RemoveCompanyMemberResponse = RemoveCompanyMemberResponses[keyof RemoveCompanyMemberResponses];

export type UpdateCompanyMemberRoleData = {
    body: UpdateRoleBodyWritable;
    path: {
        userId: number;
    };
    query?: never;
    url: '/api/companies/members/{userId}/role';
};

export type UpdateCompanyMemberRoleErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type UpdateCompanyMemberRoleError = UpdateCompanyMemberRoleErrors[keyof UpdateCompanyMemberRoleErrors];

export type UpdateCompanyMemberRoleResponses = {
    /**
     * No Content
     */
    204: void;
};

export type UpdateCompanyMemberRoleResponse = UpdateCompanyMemberRoleResponses[keyof UpdateCompanyMemberRoleResponses];

export type ListCompanyRolesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/companies/roles';
};

export type ListCompanyRolesErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type ListCompanyRolesError = ListCompanyRolesErrors[keyof ListCompanyRolesErrors];

export type ListCompanyRolesResponses = {
    /**
     * OK
     */
    200: RolesResponseReadable;
};

export type ListCompanyRolesResponse = ListCompanyRolesResponses[keyof ListCompanyRolesResponses];

export type SelectCompanyData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/companies/{id}/select';
};

export type SelectCompanyErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type SelectCompanyError = SelectCompanyErrors[keyof SelectCompanyErrors];

export type SelectCompanyResponses = {
    /**
     * No Content
     */
    204: void;
};

export type SelectCompanyResponse = SelectCompanyResponses[keyof SelectCompanyResponses];

export type ListFeatureFlagsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/feature-flags';
};

export type ListFeatureFlagsErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type ListFeatureFlagsError = ListFeatureFlagsErrors[keyof ListFeatureFlagsErrors];

export type ListFeatureFlagsResponses = {
    /**
     * OK
     */
    200: FlagListResponseReadable;
};

export type ListFeatureFlagsResponse = ListFeatureFlagsResponses[keyof ListFeatureFlagsResponses];

export type AdminListFeatureFlagsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/feature-flags/admin';
};

export type AdminListFeatureFlagsErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type AdminListFeatureFlagsError = AdminListFeatureFlagsErrors[keyof AdminListFeatureFlagsErrors];

export type AdminListFeatureFlagsResponses = {
    /**
     * OK
     */
    200: AdminContextResponseReadable;
};

export type AdminListFeatureFlagsResponse = AdminListFeatureFlagsResponses[keyof AdminListFeatureFlagsResponses];

export type AdminUpsertFeatureFlagsData = {
    body: UpsertRequestWritable;
    path?: never;
    query?: never;
    url: '/api/feature-flags/admin';
};

export type AdminUpsertFeatureFlagsErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type AdminUpsertFeatureFlagsError = AdminUpsertFeatureFlagsErrors[keyof AdminUpsertFeatureFlagsErrors];

export type AdminUpsertFeatureFlagsResponses = {
    /**
     * OK
     */
    200: UpsertResponseReadable;
};

export type AdminUpsertFeatureFlagsResponse = AdminUpsertFeatureFlagsResponses[keyof AdminUpsertFeatureFlagsResponses];

export type GetUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type GetUserMeErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type GetUserMeError = GetUserMeErrors[keyof GetUserMeErrors];

export type GetUserMeResponses = {
    /**
     * OK
     */
    200: ProfileReadable;
};

export type GetUserMeResponse = GetUserMeResponses[keyof GetUserMeResponses];

export type UpdateUserMeData = {
    body: UpdateProfileRequestWritable;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type UpdateUserMeErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type UpdateUserMeError = UpdateUserMeErrors[keyof UpdateUserMeErrors];

export type UpdateUserMeResponses = {
    /**
     * OK
     */
    200: ProfileReadable;
};

export type UpdateUserMeResponse = UpdateUserMeResponses[keyof UpdateUserMeResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};