// This file is auto-generated by @hey-api/openapi-ts

export type ApiKeyCreateRequestReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    name: string;
};

export type ApiKeyCreateRequestWritable = {
    name: string;
};

export type ApiKeyCreateResponseReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    apiKey: ApiKeyInfo;
};

export type ApiKeyCreateResponseWritable = {
    apiKey: ApiKeyInfo;
};

export type ApiKeyInfo = {
    createdAt: string;
    id: number;
    lastUsedAt?: string;
    name: string;
    prefix: string;
    revokedAt?: string;
    token?: string;
};

export type ApiKeyListResponseReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    apiKeys: Array<ApiKeyInfo> | null;
};

export type ApiKeyListResponseWritable = {
    apiKeys: Array<ApiKeyInfo> | null;
};

export type AddMemberRequestReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    email: string;
    name?: string;
};

export type AddMemberRequestWritable = {
    email: string;
    name?: string;
};

export type AdminContextResponseReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    companies: Array<CompanyOption> | null;
    flags: Array<AdminFlag> | null;
    suggestedKeys: Array<string> | null;
};

export type AdminContextResponseWritable = {
    companies: Array<CompanyOption> | null;
    flags: Array<AdminFlag> | null;
    suggestedKeys: Array<string> | null;
};

export type AdminFlag = {
    companyId: number;
    companyName: string;
    enabled: boolean;
    flagKey: string;
    id: number;
    updatedAt: string;
};

export type AuthProfileReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    email: string;
    id: number;
    name: string;
    selectedCompanyId: number;
};

export type AuthProfileWritable = {
    email: string;
    id: number;
    name: string;
    selectedCompanyId: number;
};

export type CompanyCreateRequestReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    name: string;
};

export type CompanyCreateRequestWritable = {
    name: string;
};

export type CompanyCreateResponseReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    company: CompanyInfo;
};

export type CompanyCreateResponseWritable = {
    company: CompanyInfo;
};

export type CompanyInfo = {
    createdAt: string;
    id: number;
    isOwner: boolean;
    name: string;
    role: string;
};

export type CompanyListResponseReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    companies: Array<CompanyInfo> | null;
};

export type CompanyListResponseWritable = {
    companies: Array<CompanyInfo> | null;
};

export type CompanyOption = {
    id: number;
    name: string;
};

export type CreateEventRequestReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    cycles: Array<CycleInput> | null;
    description?: string;
    forms: Array<FormInput> | null;
    members?: Array<string> | null;
    name: string;
    visibility: string;
};

export type CreateEventRequestWritable = {
    cycles: Array<CycleInput> | null;
    description?: string;
    forms: Array<FormInput> | null;
    members?: Array<string> | null;
    name: string;
    visibility: string;
};

export type CycleAverageResult = {
    average: number;
    cycleId: number;
    formId: number;
};

export type CycleInfo = {
    eventId: number;
    id: number;
    name: string;
    orderIndex: number;
};

export type CycleInput = {
    name: string;
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModelReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type ErrorModelWritable = {
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type EventDetailReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    companyId: number;
    createdAt: string;
    currentStage: string;
    cycles: Array<CycleInfo> | null;
    description?: string;
    forms: Array<FormInfo> | null;
    hostId: number;
    id: number;
    name: string;
    status: string;
    updatedAt: string;
    visibility: string;
};

export type EventDetailWritable = {
    companyId: number;
    createdAt: string;
    currentStage: string;
    cycles: Array<CycleInfo> | null;
    description?: string;
    forms: Array<FormInfo> | null;
    hostId: number;
    id: number;
    name: string;
    status: string;
    updatedAt: string;
    visibility: string;
};

export type EventInfo = {
    companyId: number;
    createdAt: string;
    currentStage: string;
    description?: string;
    hostId: number;
    id: number;
    name: string;
    status: string;
    updatedAt: string;
    visibility: string;
};

export type FlagListResponseReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    flags: {
        [key: string]: boolean;
    };
};

export type FlagListResponseWritable = {
    flags: {
        [key: string]: boolean;
    };
};

export type FormInfo = {
    eventId: number;
    id: number;
    label: string;
    orderIndex: number;
    type: string;
};

export type FormInput = {
    label: string;
    type: string;
};

export type FreeTextResult = {
    cycleId: number;
    formId: number;
    texts: Array<string> | null;
};

export type InviteRequestReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    email: string;
    name: string;
    role: string;
};

export type InviteRequestWritable = {
    email: string;
    name: string;
    role: string;
};

export type InviteResponseReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    member: Member;
};

export type InviteResponseWritable = {
    member: Member;
};

export type ListEventsOutputBodyReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    events: Array<EventInfo> | null;
};

export type ListEventsOutputBodyWritable = {
    events: Array<EventInfo> | null;
};

export type LoginRequestReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    email: string;
};

export type LoginRequestWritable = {
    email: string;
};

export type Member = {
    email: string;
    joinedAt: string;
    name: string;
    role: string;
    userId: number;
};

export type MemberListResponseReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    members: Array<Member> | null;
};

export type MemberListResponseWritable = {
    members: Array<Member> | null;
};

export type MonitorResponseReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    activeCycleId?: number;
    participantCount: number;
    respondedCount: number;
};

export type MonitorResponseWritable = {
    activeCycleId?: number;
    participantCount: number;
    respondedCount: number;
};

export type NextCycleRequestReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    cycleId: number;
};

export type NextCycleRequestWritable = {
    cycleId: number;
};

export type ParticipantInfoReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    eventId: number;
    id: number;
    joinedAt: string;
    userId: number;
};

export type ParticipantInfoWritable = {
    eventId: number;
    id: number;
    joinedAt: string;
    userId: number;
};

export type ProfileReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    createdAt: string;
    email: string;
    id: number;
    name: string;
    selectedCompanyId: number;
};

export type ProfileWritable = {
    createdAt: string;
    email: string;
    id: number;
    name: string;
    selectedCompanyId: number;
};

export type RespondItemInput = {
    formId: number;
    valueNumber?: number;
    valueText?: string;
};

export type RespondRequestReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    items: Array<RespondItemInput> | null;
};

export type RespondRequestWritable = {
    items: Array<RespondItemInput> | null;
};

export type ResultsResponseReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    avgTable: Array<CycleAverageResult> | null;
    cycles: Array<CycleInfo> | null;
    forms: Array<FormInfo> | null;
    freeTexts: Array<FreeTextResult> | null;
};

export type ResultsResponseWritable = {
    avgTable: Array<CycleAverageResult> | null;
    cycles: Array<CycleInfo> | null;
    forms: Array<FormInfo> | null;
    freeTexts: Array<FreeTextResult> | null;
};

export type Role = {
    label: string;
    value: string;
};

export type RolesResponseReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    roles: Array<Role> | null;
};

export type RolesResponseWritable = {
    roles: Array<Role> | null;
};

export type SessionResponseReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    activeCycleId?: number;
    activeCycleName?: string;
    currentStage: string;
    forms: Array<FormInfo> | null;
    isParticipant: boolean;
    myResponseSubmitted: boolean;
};

export type SessionResponseWritable = {
    activeCycleId?: number;
    activeCycleName?: string;
    currentStage: string;
    forms: Array<FormInfo> | null;
    isParticipant: boolean;
    myResponseSubmitted: boolean;
};

export type StartCycleRequestReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    cycleId: number;
};

export type StartCycleRequestWritable = {
    cycleId: number;
};

export type UpdateProfileRequestReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    name: string;
};

export type UpdateProfileRequestWritable = {
    name: string;
};

export type UpdateRoleBodyReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    role: string;
};

export type UpdateRoleBodyWritable = {
    role: string;
};

export type UpsertRequestReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    allCompanies: boolean;
    companyIds: Array<number> | null;
    enabled: boolean;
    flagKey: string;
};

export type UpsertRequestWritable = {
    allCompanies: boolean;
    companyIds: Array<number> | null;
    enabled: boolean;
    flagKey: string;
};

export type UpsertResponseReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    flags: Array<AdminFlag> | null;
};

export type UpsertResponseWritable = {
    flags: Array<AdminFlag> | null;
};

export type VerifyRequestReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    email: string;
    otp: string;
};

export type VerifyRequestWritable = {
    email: string;
    otp: string;
};

export type VerifyResponseReadable = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    profile: AuthProfileReadable;
    token: string;
};

export type VerifyResponseWritable = {
    profile: AuthProfileWritable;
    token: string;
};

export type ListApiKeysData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/apikeys';
};

export type ListApiKeysErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type ListApiKeysError = ListApiKeysErrors[keyof ListApiKeysErrors];

export type ListApiKeysResponses = {
    /**
     * OK
     */
    200: ApiKeyListResponseReadable;
};

export type ListApiKeysResponse = ListApiKeysResponses[keyof ListApiKeysResponses];

export type CreateApiKeyData = {
    body: ApiKeyCreateRequestWritable;
    path?: never;
    query?: never;
    url: '/api/apikeys';
};

export type CreateApiKeyErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type CreateApiKeyError = CreateApiKeyErrors[keyof CreateApiKeyErrors];

export type CreateApiKeyResponses = {
    /**
     * Created
     */
    201: ApiKeyCreateResponseReadable;
};

export type CreateApiKeyResponse = CreateApiKeyResponses[keyof CreateApiKeyResponses];

export type RevokeApiKeyData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/apikeys/{id}/revoke';
};

export type RevokeApiKeyErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type RevokeApiKeyError = RevokeApiKeyErrors[keyof RevokeApiKeyErrors];

export type RevokeApiKeyResponses = {
    /**
     * No Content
     */
    204: void;
};

export type RevokeApiKeyResponse = RevokeApiKeyResponses[keyof RevokeApiKeyResponses];

export type LoginRequestData = {
    body: LoginRequestWritable;
    path?: never;
    query?: never;
    url: '/api/auth/login-request';
};

export type LoginRequestErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type LoginRequestError = LoginRequestErrors[keyof LoginRequestErrors];

export type LoginRequestResponses = {
    /**
     * No Content
     */
    204: void;
};

export type LoginRequestResponse = LoginRequestResponses[keyof LoginRequestResponses];

export type LoginVerifyData = {
    body: VerifyRequestWritable;
    path?: never;
    query?: never;
    url: '/api/auth/login-verify';
};

export type LoginVerifyErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type LoginVerifyError = LoginVerifyErrors[keyof LoginVerifyErrors];

export type LoginVerifyResponses = {
    /**
     * OK
     */
    200: VerifyResponseReadable;
};

export type LoginVerifyResponse = LoginVerifyResponses[keyof LoginVerifyResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * No Content
     */
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type GetMeErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
    /**
     * OK
     */
    200: AuthProfileReadable;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type ListCompaniesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/companies';
};

export type ListCompaniesErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type ListCompaniesError = ListCompaniesErrors[keyof ListCompaniesErrors];

export type ListCompaniesResponses = {
    /**
     * OK
     */
    200: CompanyListResponseReadable;
};

export type ListCompaniesResponse = ListCompaniesResponses[keyof ListCompaniesResponses];

export type CreateCompanyData = {
    body: CompanyCreateRequestWritable;
    path?: never;
    query?: never;
    url: '/api/companies';
};

export type CreateCompanyErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type CreateCompanyError = CreateCompanyErrors[keyof CreateCompanyErrors];

export type CreateCompanyResponses = {
    /**
     * Created
     */
    201: CompanyCreateResponseReadable;
};

export type CreateCompanyResponse = CreateCompanyResponses[keyof CreateCompanyResponses];

export type InviteCompanyMemberData = {
    body: InviteRequestWritable;
    path?: never;
    query?: never;
    url: '/api/companies/invite';
};

export type InviteCompanyMemberErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type InviteCompanyMemberError = InviteCompanyMemberErrors[keyof InviteCompanyMemberErrors];

export type InviteCompanyMemberResponses = {
    /**
     * Created
     */
    201: InviteResponseReadable;
};

export type InviteCompanyMemberResponse = InviteCompanyMemberResponses[keyof InviteCompanyMemberResponses];

export type ListCompanyMembersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/companies/members';
};

export type ListCompanyMembersErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type ListCompanyMembersError = ListCompanyMembersErrors[keyof ListCompanyMembersErrors];

export type ListCompanyMembersResponses = {
    /**
     * OK
     */
    200: MemberListResponseReadable;
};

export type ListCompanyMembersResponse = ListCompanyMembersResponses[keyof ListCompanyMembersResponses];

export type RemoveCompanyMemberData = {
    body?: never;
    path: {
        userId: number;
    };
    query?: never;
    url: '/api/companies/members/{userId}';
};

export type RemoveCompanyMemberErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type RemoveCompanyMemberError = RemoveCompanyMemberErrors[keyof RemoveCompanyMemberErrors];

export type RemoveCompanyMemberResponses = {
    /**
     * No Content
     */
    204: void;
};

export type RemoveCompanyMemberResponse = RemoveCompanyMemberResponses[keyof RemoveCompanyMemberResponses];

export type UpdateCompanyMemberRoleData = {
    body: UpdateRoleBodyWritable;
    path: {
        userId: number;
    };
    query?: never;
    url: '/api/companies/members/{userId}/role';
};

export type UpdateCompanyMemberRoleErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type UpdateCompanyMemberRoleError = UpdateCompanyMemberRoleErrors[keyof UpdateCompanyMemberRoleErrors];

export type UpdateCompanyMemberRoleResponses = {
    /**
     * No Content
     */
    204: void;
};

export type UpdateCompanyMemberRoleResponse = UpdateCompanyMemberRoleResponses[keyof UpdateCompanyMemberRoleResponses];

export type ListCompanyRolesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/companies/roles';
};

export type ListCompanyRolesErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type ListCompanyRolesError = ListCompanyRolesErrors[keyof ListCompanyRolesErrors];

export type ListCompanyRolesResponses = {
    /**
     * OK
     */
    200: RolesResponseReadable;
};

export type ListCompanyRolesResponse = ListCompanyRolesResponses[keyof ListCompanyRolesResponses];

export type SelectCompanyData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/companies/{id}/select';
};

export type SelectCompanyErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type SelectCompanyError = SelectCompanyErrors[keyof SelectCompanyErrors];

export type SelectCompanyResponses = {
    /**
     * No Content
     */
    204: void;
};

export type SelectCompanyResponse = SelectCompanyResponses[keyof SelectCompanyResponses];

export type ListEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/events';
};

export type ListEventsErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type ListEventsError = ListEventsErrors[keyof ListEventsErrors];

export type ListEventsResponses = {
    /**
     * OK
     */
    200: ListEventsOutputBodyReadable;
};

export type ListEventsResponse = ListEventsResponses[keyof ListEventsResponses];

export type CreateEventData = {
    body: CreateEventRequestWritable;
    path?: never;
    query?: never;
    url: '/api/events';
};

export type CreateEventErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type CreateEventError = CreateEventErrors[keyof CreateEventErrors];

export type CreateEventResponses = {
    /**
     * Created
     */
    201: EventDetailReadable;
};

export type CreateEventResponse = CreateEventResponses[keyof CreateEventResponses];

export type GetEventData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/events/{id}';
};

export type GetEventErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type GetEventError = GetEventErrors[keyof GetEventErrors];

export type GetEventResponses = {
    /**
     * OK
     */
    200: EventDetailReadable;
};

export type GetEventResponse = GetEventResponses[keyof GetEventResponses];

export type ActivateEventData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/events/{id}/activate';
};

export type ActivateEventErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type ActivateEventError = ActivateEventErrors[keyof ActivateEventErrors];

export type ActivateEventResponses = {
    /**
     * No Content
     */
    204: void;
};

export type ActivateEventResponse = ActivateEventResponses[keyof ActivateEventResponses];

export type EndEventData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/events/{id}/end';
};

export type EndEventErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type EndEventError = EndEventErrors[keyof EndEventErrors];

export type EndEventResponses = {
    /**
     * No Content
     */
    204: void;
};

export type EndEventResponse = EndEventResponses[keyof EndEventResponses];

export type JoinEventData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/events/{id}/join';
};

export type JoinEventErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type JoinEventError = JoinEventErrors[keyof JoinEventErrors];

export type JoinEventResponses = {
    /**
     * Created
     */
    201: ParticipantInfoReadable;
};

export type JoinEventResponse = JoinEventResponses[keyof JoinEventResponses];

export type AddEventMemberData = {
    body: AddMemberRequestWritable;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/events/{id}/members';
};

export type AddEventMemberErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type AddEventMemberError = AddEventMemberErrors[keyof AddEventMemberErrors];

export type AddEventMemberResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type RemoveEventMemberData = {
    body?: never;
    path: {
        id: number;
        userId: number;
    };
    query?: never;
    url: '/api/events/{id}/members/{userId}';
};

export type RemoveEventMemberErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type RemoveEventMemberError = RemoveEventMemberErrors[keyof RemoveEventMemberErrors];

export type RemoveEventMemberResponses = {
    /**
     * No Content
     */
    204: void;
};

export type RemoveEventMemberResponse = RemoveEventMemberResponses[keyof RemoveEventMemberResponses];

export type GetEventMonitorData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/events/{id}/monitor';
};

export type GetEventMonitorErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type GetEventMonitorError = GetEventMonitorErrors[keyof GetEventMonitorErrors];

export type GetEventMonitorResponses = {
    /**
     * OK
     */
    200: MonitorResponseReadable;
};

export type GetEventMonitorResponse = GetEventMonitorResponses[keyof GetEventMonitorResponses];

export type NextCycleData = {
    body: NextCycleRequestWritable;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/events/{id}/next-cycle';
};

export type NextCycleErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type NextCycleError = NextCycleErrors[keyof NextCycleErrors];

export type NextCycleResponses = {
    /**
     * No Content
     */
    204: void;
};

export type NextCycleResponse = NextCycleResponses[keyof NextCycleResponses];

export type RespondToCycleData = {
    body: RespondRequestWritable;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/events/{id}/respond';
};

export type RespondToCycleErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type RespondToCycleError = RespondToCycleErrors[keyof RespondToCycleErrors];

export type RespondToCycleResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type GetEventResultsData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/events/{id}/results';
};

export type GetEventResultsErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type GetEventResultsError = GetEventResultsErrors[keyof GetEventResultsErrors];

export type GetEventResultsResponses = {
    /**
     * OK
     */
    200: ResultsResponseReadable;
};

export type GetEventResultsResponse = GetEventResultsResponses[keyof GetEventResultsResponses];

export type ExportEventResultsData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/events/{id}/results/export';
};

export type ExportEventResultsErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type ExportEventResultsError = ExportEventResultsErrors[keyof ExportEventResultsErrors];

export type ExportEventResultsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetEventSessionData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/events/{id}/session';
};

export type GetEventSessionErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type GetEventSessionError = GetEventSessionErrors[keyof GetEventSessionErrors];

export type GetEventSessionResponses = {
    /**
     * OK
     */
    200: SessionResponseReadable;
};

export type GetEventSessionResponse = GetEventSessionResponses[keyof GetEventSessionResponses];

export type ShowFormData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/events/{id}/show-form';
};

export type ShowFormErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type ShowFormError = ShowFormErrors[keyof ShowFormErrors];

export type ShowFormResponses = {
    /**
     * No Content
     */
    204: void;
};

export type ShowFormResponse = ShowFormResponses[keyof ShowFormResponses];

export type StartCycleData = {
    body: StartCycleRequestWritable;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/events/{id}/start-cycle';
};

export type StartCycleErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type StartCycleError = StartCycleErrors[keyof StartCycleErrors];

export type StartCycleResponses = {
    /**
     * No Content
     */
    204: void;
};

export type StartCycleResponse = StartCycleResponses[keyof StartCycleResponses];

export type ListFeatureFlagsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/feature-flags';
};

export type ListFeatureFlagsErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type ListFeatureFlagsError = ListFeatureFlagsErrors[keyof ListFeatureFlagsErrors];

export type ListFeatureFlagsResponses = {
    /**
     * OK
     */
    200: FlagListResponseReadable;
};

export type ListFeatureFlagsResponse = ListFeatureFlagsResponses[keyof ListFeatureFlagsResponses];

export type AdminListFeatureFlagsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/feature-flags/admin';
};

export type AdminListFeatureFlagsErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type AdminListFeatureFlagsError = AdminListFeatureFlagsErrors[keyof AdminListFeatureFlagsErrors];

export type AdminListFeatureFlagsResponses = {
    /**
     * OK
     */
    200: AdminContextResponseReadable;
};

export type AdminListFeatureFlagsResponse = AdminListFeatureFlagsResponses[keyof AdminListFeatureFlagsResponses];

export type AdminUpsertFeatureFlagsData = {
    body: UpsertRequestWritable;
    path?: never;
    query?: never;
    url: '/api/feature-flags/admin';
};

export type AdminUpsertFeatureFlagsErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type AdminUpsertFeatureFlagsError = AdminUpsertFeatureFlagsErrors[keyof AdminUpsertFeatureFlagsErrors];

export type AdminUpsertFeatureFlagsResponses = {
    /**
     * OK
     */
    200: UpsertResponseReadable;
};

export type AdminUpsertFeatureFlagsResponse = AdminUpsertFeatureFlagsResponses[keyof AdminUpsertFeatureFlagsResponses];

export type GetUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type GetUserMeErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type GetUserMeError = GetUserMeErrors[keyof GetUserMeErrors];

export type GetUserMeResponses = {
    /**
     * OK
     */
    200: ProfileReadable;
};

export type GetUserMeResponse = GetUserMeResponses[keyof GetUserMeResponses];

export type UpdateUserMeData = {
    body: UpdateProfileRequestWritable;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type UpdateUserMeErrors = {
    /**
     * Error
     */
    default: ErrorModelReadable;
};

export type UpdateUserMeError = UpdateUserMeErrors[keyof UpdateUserMeErrors];

export type UpdateUserMeResponses = {
    /**
     * OK
     */
    200: ProfileReadable;
};

export type UpdateUserMeResponse = UpdateUserMeResponses[keyof UpdateUserMeResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};