// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package compiled

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         int64
	Hash       string
	Prefix     string
	Name       string
	CompanyID  int64
	CreatedBy  int64
	LastUsedAt pgtype.Timestamp
	RevokedAt  pgtype.Timestamp
	CreatedAt  pgtype.Timestamp
	DeletedAt  pgtype.Timestamp
}

type Company struct {
	ID        int64
	Name      string
	OwnerID   int64
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type CompanyMember struct {
	ID        int64
	CompanyID int64
	UserID    int64
	Role      string
	CreatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type FeatureFlag struct {
	ID        int64
	CompanyID int64
	FlagKey   string
	Enabled   bool
	Payload   []byte
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type User struct {
	ID                int64
	Email             string
	Name              string
	OtpCode           pgtype.Text
	OtpExpiresAt      pgtype.Timestamp
	SelectedCompanyID pgtype.Int8
	CreatedAt         pgtype.Timestamp
	UpdatedAt         pgtype.Timestamp
	DeletedAt         pgtype.Timestamp
}

type UserSession struct {
	ID         int64
	UserID     int64
	Token      string
	ExpiresAt  pgtype.Timestamp
	LastSeenAt pgtype.Timestamp
	CreatedAt  pgtype.Timestamp
}
