// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package compiled

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const aPIKeyCreate = `-- name: APIKeyCreate :one
INSERT INTO api_keys (hash, prefix, name, company_id, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, hash, prefix, name, company_id, created_by, last_used_at, revoked_at, created_at, deleted_at
`

type APIKeyCreateParams struct {
	Hash      string
	Prefix    string
	Name      string
	CompanyID int64
	CreatedBy int64
}

func (q *Queries) APIKeyCreate(ctx context.Context, arg APIKeyCreateParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, aPIKeyCreate,
		arg.Hash,
		arg.Prefix,
		arg.Name,
		arg.CompanyID,
		arg.CreatedBy,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.Prefix,
		&i.Name,
		&i.CompanyID,
		&i.CreatedBy,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const aPIKeyGetByID = `-- name: APIKeyGetByID :one
SELECT id, hash, prefix, name, company_id, created_by, last_used_at, revoked_at, created_at, deleted_at
FROM api_keys
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) APIKeyGetByID(ctx context.Context, id int64) (ApiKey, error) {
	row := q.db.QueryRow(ctx, aPIKeyGetByID, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.Prefix,
		&i.Name,
		&i.CompanyID,
		&i.CreatedBy,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const aPIKeyListAllActive = `-- name: APIKeyListAllActive :many
SELECT id, hash, prefix, name, company_id, created_by, last_used_at, revoked_at, created_at, deleted_at
FROM api_keys
WHERE deleted_at IS NULL AND revoked_at IS NULL
`

func (q *Queries) APIKeyListAllActive(ctx context.Context) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, aPIKeyListAllActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.Hash,
			&i.Prefix,
			&i.Name,
			&i.CompanyID,
			&i.CreatedBy,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aPIKeyListByCompany = `-- name: APIKeyListByCompany :many
SELECT id, hash, prefix, name, company_id, created_by, last_used_at, revoked_at, created_at, deleted_at
FROM api_keys
WHERE company_id = $1 AND deleted_at IS NULL AND revoked_at IS NULL
ORDER BY id DESC
`

func (q *Queries) APIKeyListByCompany(ctx context.Context, companyID int64) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, aPIKeyListByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.Hash,
			&i.Prefix,
			&i.Name,
			&i.CompanyID,
			&i.CreatedBy,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const aPIKeyResolve = `-- name: APIKeyResolve :one
SELECT
    ak.id           AS api_key_id,
    u.id            AS user_id,
    u.email         AS user_email,
    u.name          AS user_name,
    u.selected_company_id
FROM api_keys ak
JOIN users u ON u.id = ak.created_by AND u.deleted_at IS NULL
WHERE ak.hash = $1
  AND ak.deleted_at IS NULL
  AND ak.revoked_at IS NULL
`

type APIKeyResolveRow struct {
	ApiKeyID          int64
	UserID            int64
	UserEmail         string
	UserName          string
	SelectedCompanyID pgtype.Int8
}

// Resolve api key + caller user dalam satu query.
// Match user state SAAT INI (selected_company_id, name, email) — bukan
// snapshot saat key dibuat. Akses semantically identical to user session
// token; bedanya cuma persistence.
func (q *Queries) APIKeyResolve(ctx context.Context, hash string) (APIKeyResolveRow, error) {
	row := q.db.QueryRow(ctx, aPIKeyResolve, hash)
	var i APIKeyResolveRow
	err := row.Scan(
		&i.ApiKeyID,
		&i.UserID,
		&i.UserEmail,
		&i.UserName,
		&i.SelectedCompanyID,
	)
	return i, err
}

const aPIKeyRevoke = `-- name: APIKeyRevoke :exec
UPDATE api_keys
SET revoked_at = NOW()
WHERE id = $1 AND deleted_at IS NULL AND revoked_at IS NULL
`

func (q *Queries) APIKeyRevoke(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, aPIKeyRevoke, id)
	return err
}

const aPIKeyTouchLastUsed = `-- name: APIKeyTouchLastUsed :exec
UPDATE api_keys
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) APIKeyTouchLastUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, aPIKeyTouchLastUsed, id)
	return err
}

const authClearOTP = `-- name: AuthClearOTP :exec
UPDATE users
SET otp_code = NULL, otp_expires_at = NULL, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) AuthClearOTP(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, authClearOTP, id)
	return err
}

const authCreateSession = `-- name: AuthCreateSession :one
INSERT INTO user_sessions (user_id, token, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token, expires_at, last_seen_at, created_at
`

type AuthCreateSessionParams struct {
	UserID    int64
	Token     string
	ExpiresAt pgtype.Timestamp
}

func (q *Queries) AuthCreateSession(ctx context.Context, arg AuthCreateSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, authCreateSession, arg.UserID, arg.Token, arg.ExpiresAt)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const authCreateUser = `-- name: AuthCreateUser :one
INSERT INTO users (email, name)
VALUES ($1, $2)
RETURNING id, email, name, otp_code, otp_expires_at, selected_company_id, created_at, updated_at, deleted_at
`

type AuthCreateUserParams struct {
	Email string
	Name  string
}

func (q *Queries) AuthCreateUser(ctx context.Context, arg AuthCreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, authCreateUser, arg.Email, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.OtpCode,
		&i.OtpExpiresAt,
		&i.SelectedCompanyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const authDeleteAllUserSessions = `-- name: AuthDeleteAllUserSessions :exec
DELETE FROM user_sessions WHERE user_id = $1
`

func (q *Queries) AuthDeleteAllUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, authDeleteAllUserSessions, userID)
	return err
}

const authDeleteSession = `-- name: AuthDeleteSession :exec
DELETE FROM user_sessions WHERE token = $1
`

func (q *Queries) AuthDeleteSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, authDeleteSession, token)
	return err
}

const authFindUserByEmail = `-- name: AuthFindUserByEmail :one
SELECT id, email, name, otp_code, otp_expires_at, selected_company_id, created_at, updated_at, deleted_at
FROM users
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) AuthFindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, authFindUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.OtpCode,
		&i.OtpExpiresAt,
		&i.SelectedCompanyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const authFindUserBySessionToken = `-- name: AuthFindUserBySessionToken :one
SELECT u.id, u.email, u.name, u.otp_code, u.otp_expires_at, u.selected_company_id, u.created_at, u.updated_at, u.deleted_at
FROM users u
JOIN user_sessions s ON s.user_id = u.id
WHERE s.token = $1
  AND s.expires_at > NOW()
  AND u.deleted_at IS NULL
`

func (q *Queries) AuthFindUserBySessionToken(ctx context.Context, token string) (User, error) {
	row := q.db.QueryRow(ctx, authFindUserBySessionToken, token)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.OtpCode,
		&i.OtpExpiresAt,
		&i.SelectedCompanyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const authFirstCompanyForUser = `-- name: AuthFirstCompanyForUser :one
SELECT cm.company_id
FROM company_members cm
JOIN companies c ON c.id = cm.company_id AND c.deleted_at IS NULL
WHERE cm.user_id = $1 AND cm.deleted_at IS NULL
ORDER BY cm.id
LIMIT 1
`

// Untuk auto-select company pertama saat user login tanpa selected_company.
// Order by id biar deterministic.
func (q *Queries) AuthFirstCompanyForUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, authFirstCompanyForUser, userID)
	var company_id int64
	err := row.Scan(&company_id)
	return company_id, err
}

const authSetOTP = `-- name: AuthSetOTP :exec
UPDATE users
SET otp_code = $2, otp_expires_at = $3, updated_at = NOW()
WHERE id = $1
`

type AuthSetOTPParams struct {
	ID           int64
	OtpCode      pgtype.Text
	OtpExpiresAt pgtype.Timestamp
}

func (q *Queries) AuthSetOTP(ctx context.Context, arg AuthSetOTPParams) error {
	_, err := q.db.Exec(ctx, authSetOTP, arg.ID, arg.OtpCode, arg.OtpExpiresAt)
	return err
}

const authSetSelectedCompany = `-- name: AuthSetSelectedCompany :exec
UPDATE users
SET selected_company_id = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type AuthSetSelectedCompanyParams struct {
	ID                int64
	SelectedCompanyID pgtype.Int8
}

func (q *Queries) AuthSetSelectedCompany(ctx context.Context, arg AuthSetSelectedCompanyParams) error {
	_, err := q.db.Exec(ctx, authSetSelectedCompany, arg.ID, arg.SelectedCompanyID)
	return err
}

const companyAddMember = `-- name: CompanyAddMember :one
INSERT INTO company_members (company_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, company_id, user_id, role, created_at, deleted_at
`

type CompanyAddMemberParams struct {
	CompanyID int64
	UserID    int64
	Role      string
}

func (q *Queries) CompanyAddMember(ctx context.Context, arg CompanyAddMemberParams) (CompanyMember, error) {
	row := q.db.QueryRow(ctx, companyAddMember, arg.CompanyID, arg.UserID, arg.Role)
	var i CompanyMember
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const companyCreate = `-- name: CompanyCreate :one
INSERT INTO companies (name, owner_id)
VALUES ($1, $2)
RETURNING id, name, owner_id, created_at, updated_at, deleted_at
`

type CompanyCreateParams struct {
	Name    string
	OwnerID int64
}

func (q *Queries) CompanyCreate(ctx context.Context, arg CompanyCreateParams) (Company, error) {
	row := q.db.QueryRow(ctx, companyCreate, arg.Name, arg.OwnerID)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const companyCreateUser = `-- name: CompanyCreateUser :one
INSERT INTO users (email, name)
VALUES ($1, $2)
RETURNING id, email, name, otp_code, otp_expires_at, selected_company_id, created_at, updated_at, deleted_at
`

type CompanyCreateUserParams struct {
	Email string
	Name  string
}

func (q *Queries) CompanyCreateUser(ctx context.Context, arg CompanyCreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, companyCreateUser, arg.Email, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.OtpCode,
		&i.OtpExpiresAt,
		&i.SelectedCompanyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const companyExistsOwnedBy = `-- name: CompanyExistsOwnedBy :one
SELECT EXISTS(
    SELECT 1 FROM companies
    WHERE owner_id = $1 AND deleted_at IS NULL
) AS owns
`

// True kalau user pernah jadi owner suatu company. Dipakai untuk gate
// "siapa yang boleh create company baru" — non-owner harus di-invite.
func (q *Queries) CompanyExistsOwnedBy(ctx context.Context, ownerID int64) (bool, error) {
	row := q.db.QueryRow(ctx, companyExistsOwnedBy, ownerID)
	var owns bool
	err := row.Scan(&owns)
	return owns, err
}

const companyFindUserByEmail = `-- name: CompanyFindUserByEmail :one
SELECT id, email, name, otp_code, otp_expires_at, selected_company_id, created_at, updated_at, deleted_at
FROM users
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) CompanyFindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, companyFindUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.OtpCode,
		&i.OtpExpiresAt,
		&i.SelectedCompanyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const companyGetByID = `-- name: CompanyGetByID :one
SELECT id, name, owner_id, created_at, updated_at, deleted_at
FROM companies
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) CompanyGetByID(ctx context.Context, id int64) (Company, error) {
	row := q.db.QueryRow(ctx, companyGetByID, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const companyGetMembership = `-- name: CompanyGetMembership :one
SELECT id, company_id, user_id, role, created_at, deleted_at
FROM company_members
WHERE company_id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type CompanyGetMembershipParams struct {
	CompanyID int64
	UserID    int64
}

func (q *Queries) CompanyGetMembership(ctx context.Context, arg CompanyGetMembershipParams) (CompanyMember, error) {
	row := q.db.QueryRow(ctx, companyGetMembership, arg.CompanyID, arg.UserID)
	var i CompanyMember
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const companyListByUser = `-- name: CompanyListByUser :many
SELECT
    c.id,
    c.name,
    c.owner_id,
    c.created_at,
    c.updated_at,
    c.deleted_at,
    cm.role
FROM companies c
JOIN company_members cm ON cm.company_id = c.id AND cm.deleted_at IS NULL
WHERE cm.user_id = $1
  AND c.deleted_at IS NULL
ORDER BY c.id
`

type CompanyListByUserRow struct {
	ID        int64
	Name      string
	OwnerID   int64
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
	Role      string
}

func (q *Queries) CompanyListByUser(ctx context.Context, userID int64) ([]CompanyListByUserRow, error) {
	rows, err := q.db.Query(ctx, companyListByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompanyListByUserRow
	for rows.Next() {
		var i CompanyListByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const companyListMembers = `-- name: CompanyListMembers :many
SELECT
    cm.user_id,
    cm.role,
    cm.created_at AS joined_at,
    u.email,
    u.name
FROM company_members cm
JOIN users u ON u.id = cm.user_id AND u.deleted_at IS NULL
WHERE cm.company_id = $1 AND cm.deleted_at IS NULL
ORDER BY cm.id
`

type CompanyListMembersRow struct {
	UserID   int64
	Role     string
	JoinedAt pgtype.Timestamp
	Email    string
	Name     string
}

func (q *Queries) CompanyListMembers(ctx context.Context, companyID int64) ([]CompanyListMembersRow, error) {
	rows, err := q.db.Query(ctx, companyListMembers, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompanyListMembersRow
	for rows.Next() {
		var i CompanyListMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.Email,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const companyRemoveMember = `-- name: CompanyRemoveMember :exec
UPDATE company_members
SET deleted_at = NOW()
WHERE company_id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type CompanyRemoveMemberParams struct {
	CompanyID int64
	UserID    int64
}

func (q *Queries) CompanyRemoveMember(ctx context.Context, arg CompanyRemoveMemberParams) error {
	_, err := q.db.Exec(ctx, companyRemoveMember, arg.CompanyID, arg.UserID)
	return err
}

const companySetUserSelectedCompany = `-- name: CompanySetUserSelectedCompany :exec
UPDATE users
SET selected_company_id = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type CompanySetUserSelectedCompanyParams struct {
	ID                int64
	SelectedCompanyID pgtype.Int8
}

func (q *Queries) CompanySetUserSelectedCompany(ctx context.Context, arg CompanySetUserSelectedCompanyParams) error {
	_, err := q.db.Exec(ctx, companySetUserSelectedCompany, arg.ID, arg.SelectedCompanyID)
	return err
}

const companyUpdateMemberRole = `-- name: CompanyUpdateMemberRole :exec
UPDATE company_members
SET role = $3
WHERE company_id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type CompanyUpdateMemberRoleParams struct {
	CompanyID int64
	UserID    int64
	Role      string
}

func (q *Queries) CompanyUpdateMemberRole(ctx context.Context, arg CompanyUpdateMemberRoleParams) error {
	_, err := q.db.Exec(ctx, companyUpdateMemberRole, arg.CompanyID, arg.UserID, arg.Role)
	return err
}

const fFAdminListAll = `-- name: FFAdminListAll :many
SELECT
    ff.id,
    ff.company_id,
    c.name AS company_name,
    ff.flag_key,
    ff.enabled,
    ff.updated_at
FROM feature_flags ff
JOIN companies c ON c.id = ff.company_id AND c.deleted_at IS NULL
ORDER BY c.name, ff.flag_key
`

type FFAdminListAllRow struct {
	ID          int64
	CompanyID   int64
	CompanyName string
	FlagKey     string
	Enabled     bool
	UpdatedAt   pgtype.Timestamp
}

// Admin view — semua flag dari semua company, JOIN companies untuk
// display name. Order: company_name, flag_key supaya stable.
func (q *Queries) FFAdminListAll(ctx context.Context) ([]FFAdminListAllRow, error) {
	rows, err := q.db.Query(ctx, fFAdminListAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FFAdminListAllRow
	for rows.Next() {
		var i FFAdminListAllRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CompanyName,
			&i.FlagKey,
			&i.Enabled,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fFIsAdmin = `-- name: FFIsAdmin :one
SELECT EXISTS(
    SELECT 1 FROM company_members
    WHERE company_id = $1 AND user_id = $2
      AND role = 'admin'
      AND deleted_at IS NULL
) AS is_admin
`

type FFIsAdminParams struct {
	CompanyID int64
	UserID    int64
}

// Admin role check untuk admin-only endpoints. TRUE kalau user adalah
// admin di company. Ditulis ulang di sini (bukan share dengan
// company.requireAdmin) karena domain TIDAK import domain lain.
func (q *Queries) FFIsAdmin(ctx context.Context, arg FFIsAdminParams) (bool, error) {
	row := q.db.QueryRow(ctx, fFIsAdmin, arg.CompanyID, arg.UserID)
	var is_admin bool
	err := row.Scan(&is_admin)
	return is_admin, err
}

const fFListAll = `-- name: FFListAll :many
SELECT id, company_id, flag_key, enabled, updated_at
FROM feature_flags
`

type FFListAllRow struct {
	ID        int64
	CompanyID int64
	FlagKey   string
	Enabled   bool
	UpdatedAt pgtype.Timestamp
}

// All flags semua company — dipakai cron refresh untuk rebuild snapshot cache.
func (q *Queries) FFListAll(ctx context.Context) ([]FFListAllRow, error) {
	rows, err := q.db.Query(ctx, fFListAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FFListAllRow
	for rows.Next() {
		var i FFListAllRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.FlagKey,
			&i.Enabled,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fFListCompaniesAdmin = `-- name: FFListCompaniesAdmin :many
SELECT id, name
FROM companies
WHERE deleted_at IS NULL
ORDER BY id
`

type FFListCompaniesAdminRow struct {
	ID   int64
	Name string
}

// Daftar company untuk multi-select target di create dialog.
func (q *Queries) FFListCompaniesAdmin(ctx context.Context) ([]FFListCompaniesAdminRow, error) {
	rows, err := q.db.Query(ctx, fFListCompaniesAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FFListCompaniesAdminRow
	for rows.Next() {
		var i FFListCompaniesAdminRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fFListDistinctKeys = `-- name: FFListDistinctKeys :many
SELECT DISTINCT flag_key
FROM feature_flags
ORDER BY flag_key
`

// Daftar flag_key unik (across all companies) untuk autocomplete.
func (q *Queries) FFListDistinctKeys(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, fFListDistinctKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var flag_key string
		if err := rows.Scan(&flag_key); err != nil {
			return nil, err
		}
		items = append(items, flag_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fFUpsert = `-- name: FFUpsert :one
INSERT INTO feature_flags (company_id, flag_key, enabled)
VALUES ($1, $2, $3)
ON CONFLICT (company_id, flag_key)
DO UPDATE SET enabled = EXCLUDED.enabled, updated_at = NOW()
RETURNING id, company_id, flag_key, enabled, updated_at
`

type FFUpsertParams struct {
	CompanyID int64
	FlagKey   string
	Enabled   bool
}

type FFUpsertRow struct {
	ID        int64
	CompanyID int64
	FlagKey   string
	Enabled   bool
	UpdatedAt pgtype.Timestamp
}

// Toggle / create flag. Pakai ON CONFLICT (company_id, flag_key) DO UPDATE
// supaya idempotent.
func (q *Queries) FFUpsert(ctx context.Context, arg FFUpsertParams) (FFUpsertRow, error) {
	row := q.db.QueryRow(ctx, fFUpsert, arg.CompanyID, arg.FlagKey, arg.Enabled)
	var i FFUpsertRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.FlagKey,
		&i.Enabled,
		&i.UpdatedAt,
	)
	return i, err
}

const ratingAddEventMember = `-- name: RatingAddEventMember :exec
INSERT INTO event_members (event_id, user_id) VALUES ($1, $2)
`

type RatingAddEventMemberParams struct {
	EventID int64
	UserID  int64
}

func (q *Queries) RatingAddEventMember(ctx context.Context, arg RatingAddEventMemberParams) error {
	_, err := q.db.Exec(ctx, ratingAddEventMember, arg.EventID, arg.UserID)
	return err
}

const ratingBulkInsertCycles = `-- name: RatingBulkInsertCycles :many
INSERT INTO cycles (event_id, name, order_index)
SELECT $1, unnest($2::text[]), generate_series(0, array_length($2::text[], 1) - 1)
RETURNING id, event_id, name, order_index
`

type RatingBulkInsertCyclesParams struct {
	EventID int64
	Column2 []string
}

func (q *Queries) RatingBulkInsertCycles(ctx context.Context, arg RatingBulkInsertCyclesParams) ([]Cycle, error) {
	rows, err := q.db.Query(ctx, ratingBulkInsertCycles, arg.EventID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cycle
	for rows.Next() {
		var i Cycle
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.OrderIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ratingBulkInsertForms = `-- name: RatingBulkInsertForms :many
INSERT INTO forms (event_id, type, label, order_index)
SELECT $1, unnest($2::text[]), unnest($3::text[]), generate_series(0, array_length($2::text[], 1) - 1)
RETURNING id, event_id, type, label, order_index
`

type RatingBulkInsertFormsParams struct {
	EventID int64
	Column2 []string
	Column3 []string
}

func (q *Queries) RatingBulkInsertForms(ctx context.Context, arg RatingBulkInsertFormsParams) ([]Form, error) {
	rows, err := q.db.Query(ctx, ratingBulkInsertForms, arg.EventID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Form
	for rows.Next() {
		var i Form
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Type,
			&i.Label,
			&i.OrderIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ratingCreateEvent = `-- name: RatingCreateEvent :one
INSERT INTO events (company_id, host_id, name, description, visibility, status, current_stage)
VALUES ($1, $2, $3, $4, $5, 'draft', 'idle')
RETURNING id, company_id, host_id, name, description, visibility, status, current_stage, active_cycle_id, created_at, updated_at
`

type RatingCreateEventParams struct {
	CompanyID   int64
	HostID      int64
	Name        string
	Description pgtype.Text
	Visibility  string
}

func (q *Queries) RatingCreateEvent(ctx context.Context, arg RatingCreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, ratingCreateEvent,
		arg.CompanyID,
		arg.HostID,
		arg.Name,
		arg.Description,
		arg.Visibility,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.HostID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.Status,
		&i.CurrentStage,
		&i.ActiveCycleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ratingCreateUser = `-- name: RatingCreateUser :one
INSERT INTO users (email, name) VALUES ($1, $2) RETURNING id, email, name
`

type RatingCreateUserParams struct {
	Email string
	Name  string
}

type RatingCreateUserRow struct {
	ID    int64
	Email string
	Name  string
}

func (q *Queries) RatingCreateUser(ctx context.Context, arg RatingCreateUserParams) (RatingCreateUserRow, error) {
	row := q.db.QueryRow(ctx, ratingCreateUser, arg.Email, arg.Name)
	var i RatingCreateUserRow
	err := row.Scan(&i.ID, &i.Email, &i.Name)
	return i, err
}

const ratingFindUserByEmail = `-- name: RatingFindUserByEmail :one
SELECT id, email, name FROM users WHERE email = $1 AND deleted_at IS NULL
`

type RatingFindUserByEmailRow struct {
	ID    int64
	Email string
	Name  string
}

func (q *Queries) RatingFindUserByEmail(ctx context.Context, email string) (RatingFindUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, ratingFindUserByEmail, email)
	var i RatingFindUserByEmailRow
	err := row.Scan(&i.ID, &i.Email, &i.Name)
	return i, err
}

const ratingGetEvent = `-- name: RatingGetEvent :one
SELECT id, company_id, host_id, name, description, visibility, status, current_stage, active_cycle_id, created_at, updated_at FROM events
WHERE id = $1 AND company_id = $2
  AND (visibility = 'public' OR host_id = $3 OR EXISTS (
    SELECT 1 FROM event_members WHERE event_id = events.id AND user_id = $3
  ))
`

type RatingGetEventParams struct {
	ID        int64
	CompanyID int64
	HostID    int64
}

func (q *Queries) RatingGetEvent(ctx context.Context, arg RatingGetEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, ratingGetEvent, arg.ID, arg.CompanyID, arg.HostID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.HostID,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.Status,
		&i.CurrentStage,
		&i.ActiveCycleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ratingGetEventCycles = `-- name: RatingGetEventCycles :many
SELECT id, event_id, name, order_index FROM cycles WHERE event_id = $1 ORDER BY order_index
`

func (q *Queries) RatingGetEventCycles(ctx context.Context, eventID int64) ([]Cycle, error) {
	rows, err := q.db.Query(ctx, ratingGetEventCycles, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cycle
	for rows.Next() {
		var i Cycle
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.OrderIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ratingGetEventForms = `-- name: RatingGetEventForms :many
SELECT id, event_id, type, label, order_index FROM forms WHERE event_id = $1 ORDER BY order_index
`

func (q *Queries) RatingGetEventForms(ctx context.Context, eventID int64) ([]Form, error) {
	rows, err := q.db.Query(ctx, ratingGetEventForms, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Form
	for rows.Next() {
		var i Form
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Type,
			&i.Label,
			&i.OrderIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ratingGetEventMember = `-- name: RatingGetEventMember :one
SELECT event_id, user_id FROM event_members WHERE event_id = $1 AND user_id = $2
`

type RatingGetEventMemberParams struct {
	EventID int64
	UserID  int64
}

func (q *Queries) RatingGetEventMember(ctx context.Context, arg RatingGetEventMemberParams) (EventMember, error) {
	row := q.db.QueryRow(ctx, ratingGetEventMember, arg.EventID, arg.UserID)
	var i EventMember
	err := row.Scan(&i.EventID, &i.UserID)
	return i, err
}

const ratingListEvents = `-- name: RatingListEvents :many
SELECT id, company_id, host_id, name, description, visibility, status, current_stage, active_cycle_id, created_at, updated_at FROM events
WHERE company_id = $1
  AND (visibility = 'public' OR host_id = $2 OR EXISTS (
    SELECT 1 FROM event_members WHERE event_id = events.id AND user_id = $2
  ))
ORDER BY created_at DESC
`

type RatingListEventsParams struct {
	CompanyID int64
	HostID    int64
}

func (q *Queries) RatingListEvents(ctx context.Context, arg RatingListEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, ratingListEvents, arg.CompanyID, arg.HostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.HostID,
			&i.Name,
			&i.Description,
			&i.Visibility,
			&i.Status,
			&i.CurrentStage,
			&i.ActiveCycleID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ratingRemoveEventMember = `-- name: RatingRemoveEventMember :exec
DELETE FROM event_members WHERE event_id = $1 AND user_id = $2
`

type RatingRemoveEventMemberParams struct {
	EventID int64
	UserID  int64
}

func (q *Queries) RatingRemoveEventMember(ctx context.Context, arg RatingRemoveEventMemberParams) error {
	_, err := q.db.Exec(ctx, ratingRemoveEventMember, arg.EventID, arg.UserID)
	return err
}

const userGetByID = `-- name: UserGetByID :one
SELECT id, email, name, otp_code, otp_expires_at, selected_company_id, created_at, updated_at, deleted_at
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) UserGetByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, userGetByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.OtpCode,
		&i.OtpExpiresAt,
		&i.SelectedCompanyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const userSetSelectedCompany = `-- name: UserSetSelectedCompany :exec
UPDATE users
SET selected_company_id = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UserSetSelectedCompanyParams struct {
	ID                int64
	SelectedCompanyID pgtype.Int8
}

func (q *Queries) UserSetSelectedCompany(ctx context.Context, arg UserSetSelectedCompanyParams) error {
	_, err := q.db.Exec(ctx, userSetSelectedCompany, arg.ID, arg.SelectedCompanyID)
	return err
}

const userUpdateName = `-- name: UserUpdateName :exec
UPDATE users
SET name = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UserUpdateNameParams struct {
	ID   int64
	Name string
}

func (q *Queries) UserUpdateName(ctx context.Context, arg UserUpdateNameParams) error {
	_, err := q.db.Exec(ctx, userUpdateName, arg.ID, arg.Name)
	return err
}
